---
- name: Ensure instances are present
  ansible.builtin.include_tasks:
    file: present.yml
  when: gcp_mode == 'provision'

- name: Ensure instances are absent
  ansible.builtin.include_tasks:
    file: absent.yml
  when: gcp_mode == 'deprovision'
