---
- name: Ensure AWS network objects are present
  hosts: awsclient
  become: false
  gather_facts: false
  vars:
    aws_mode: provision

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars/aws

    - name: Provision networks on AWS
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.aws_network

    - name: Provision subnets on AWS
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.aws_subnet

    - name: Provision security groups on AWS
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.aws_securitygroup
