---
- name: Ensure Azure network objects are present
  hosts: azureclient
  become: false
  gather_facts: false
  vars:
    azure_mode: provision

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars/azure

    - name: Provision networks on Azure
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.azure_network

    - name: Provision security groups on Azure
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.azure_securitygroup

    - name: Provision subnets on Azure
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.azure_subnet
