---
- name: Ensure GCP instances are at desired state
  hosts: gcpclient
  become: false
  gather_facts: false
  vars:
    gcp_mode: provision

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars/gcp

    - name: Ensure instances are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_instance
