---
- name: Ensure GCP network objects are present
  hosts: gcpclient
  become: false
  gather_facts: false
  vars:
    gcp_mode: provision

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars/gcp
      tags:
        - always

    - name: Ensure networks are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_network

    - name: Ensure firewalls are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_firewall
