---
- name: Ensure GCP networking is configured and at desired state
  hosts: gcpclient
  become: false
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars
      tags:
        - always

    - name: Ensure networks are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_network
      loop: "{{ gcp_networks }}"
      loop_control:
        loop_var: gcp_net
      vars:
        gcp_network_name: "{{ gcp_net.gcp_network_name }}"
        gcp_network_state: "{{ gcp_net.gcp_network_state }}"
        gcp_network_auto_create_subnets: "{{ gcp_net.gcp_network_auto_create_subnets | default(omit) }}"
        gcp_network_description: "{{ gcp_net.gcp_network_description | default(omit) }}"
        gcp_network_mtu: "{{ gcp_net.gcp_network_mtu | default(omit) }}"
      when: gcp_net.gcp_network_state == 'present'
      tags:
        - gcp_network_provision

    - name: Ensure firewalls are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_firewall
      loop: "{{ gcp_firewalls }}"
      loop_control:
        loop_var: gcp_fw
      vars:
        gcp_firewall_name: "{{ gcp_fw.gcp_firewall_name }}"
        gcp_firewall_allowed: "{{ gcp_fw.gcp_firewall_allowed | default(omit) }}"
        gcp_firewall_target_tags: "{{ gcp_fw.gcp_firewall_target_tags | default(omit) }}"
        gcp_firewall_source_tags: "{{ gcp_fw.gcp_firewall_source_tags | default(omit) }}"
        gcp_firewall_source_ranges: "{{ gcp_fw.gcp_firewall_source_ranges | default(omit) }}"
        gcp_firewall_state: "{{ gcp_fw.gcp_firewall_state }}"
      when: gcp_fw.gcp_firewall_state == 'present'
      tags:
        - gcp_network_provision

    - name: Ensure firewalls are absent
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_firewall
      loop: "{{ gcp_firewalls }}"
      loop_control:
        loop_var: gcp_fw
      vars:
        gcp_firewall_name: "{{ gcp_fw.gcp_firewall_name }}"
        gcp_firewall_state: "{{ gcp_fw.gcp_firewall_state }}"
      when: gcp_fw.gcp_firewall_state == 'absent'
      tags:
        - gcp_network_deprovision

    - name: Ensure networks are absent
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_network
      loop: "{{ gcp_networks }}"
      loop_control:
        loop_var: gcp_net
      vars:
        gcp_network_name: "{{ gcp_net.gcp_network_name }}"
        gcp_network_state: "{{ gcp_net.gcp_network_state }}"
      when: gcp_net.gcp_network_state == 'absent'
      tags:
        - gcp_network_deprovision
