---
- name: Ensure GCP network objects are absent
  hosts: gcpclient
  become: false
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars/gcp

    - name: Ensure firewalls are absent
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_firewall
      vars:
        gcp_network_mode: deprovision

    - name: Ensure networks are absent
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_network
      vars:
        gcp_network_mode: deprovision
