---
- name: Ensure AKS cluster is present with desired configuration
  azure.azcollection.azure_rm_aks:
    name: "{{ item.azure_aks_name }}"
    location: "{{ item.azure_aks_location | default(azure_aks_location) }}"
    resource_group: "{{ item.azure_resourcegroup_name | default(azure_resourcegroup_name) }}"
    dns_prefix: "{{ item.azure_aks_dns_prefix | default(azure_aks_dns_prefix) }}"
    agent_pool_profiles: "{{ item.azure_aks_agent_pool_profiles | default(azure_aks_agent_pool_profiles) }}"
    kubernetes_version: "{{ item.azure_aks_version | default(azure_aks_version) }}"
  loop: "{{ azure_aks_clusters | selectattr('azure_aks_state', '==', 'present') }}"
  register: __azure_aks
  async: 1000
  poll: 0
  changed_when: __azure_aks.changed

- name: Wait for AKS clusters to finish provisioning
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: __azure_aks_async_result
  until: __azure_aks_async_result.finished
  retries: 300
  delay: 6
  loop: "{{ __azure_aks.results }}"
  when: item.ansible_job_id is defined
