---
- name: Grab the VPC ID
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ item.aws_secgroup_vpc_name }}"
    region: "{{ item.aws_region | default(aws_region) }}"
  register: __aws_net 

- name: Ensure secgroup is absent
  amazon.aws.ec2_security_group:
    state: absent
    region: "{{ item.aws_region | default(aws_region) }}"
    name: "{{ item.aws_secgroup_name }}"
    vpc_id: "{{ __aws_net.vpcs.0.id }}"
