---
- name: Ensure security group is present
  ansible.builtin.include_tasks:
    file: present.yml
  when: aws_mode == 'provision'
  loop: "{{ aws_security_groups | selectattr('state', '==', 'present') }}"

- name: Ensure security group is absent
  ansible.builtin.include_tasks:
    file: absent.yml
  when: aws_mode == 'deprovision'
  loop: "{{ aws_security_groups | selectattr('state', '==', 'absent') }}"