---
- name: Ensure subnet is present
  ansible.builtin.include_tasks:
    file: present.yml
  when: aws_mode == 'provision'

- name: Ensure subnet is absent
  ansible.builtin.include_tasks:
    file: absent.yml
  when: aws_mode == 'deprovision'