---
- name: Ensure firewall exists with desired configuration
  ansible.builtin.include_tasks:
    file: present.yml
  when: gcp_mode == 'provision'

- name: Ensure firewall is absent
  ansible.builtin.include_tasks:
    file: absent.yml
  when: gcp_mode == 'deprovision'