---
- name: Ensure network is absent
  google.cloud.gcp_compute_network:
    name: "{{ item.gcp_network_name }}"
    project: "{{ item.gcp_project | default(gcp_project) }}"
    state: absent
  loop: "{{ gcp_networks | selectattr('gcp_network_state', 'match', 'absent') }}"
  async: 1000
  poll: 0
  register: __gcp_net
  changed_when: __gcp_net.changed

- name: Wait for deprovisioning to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: __gcp_net_async_result
  until: __gcp_net_async_result.finished
  retries: 100
  delay: 3
  loop: "{{ __gcp_net.results }}"
  when: item.ansible_job_id is defined
