---
- name: Create and configure instance
  google.cloud.gcp_compute_instance:
    name: "{{ gcp_compute_instance_name }}"
    zone: "{{ gcp_compute_instance_zone | default(gcp_location) }}"
    project: "{{ gcp_project }}"
    state: present
    machine_type: "{{ gcp_compute_instance_machine_type }}"
    disks: "{{ gcp_compute_instance_disks }}"
    network_interfaces: "{{ gcp_compute_instance_network_interfaces | default(omit, true) }}"
    metadata: "{{ gcp_compute_instance_metadata }}"
    labels: "{{ gcp_compute_instance_labels }}"
    deletion_protection: "{{ gcp_compute_instance_deletion_protection }}"
    tags: "{{ gcp_compute_instance_tags }}"
  loop: "{{ gcp_compute_instances }}"
  loop_control:
    loop_var: i
  async: 1000
  poll: 0
  register: __gcp_instance
  