---
- name: Grab VPC info
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ item.aws_gateway_vpc }}"
    region: "{{ item.aws_region | default(aws_region) }}"
  register: __aws_vpcs

- name: Ensure valid VPC
  ansible.builtin.assert:
    that:
      - (__aws_vpcs.vpcs | length) > 0
    fail_msg: No VPC named {{ item.aws_gateway_vpc }}
    success_msg: Found VPC named {{ item.aws_gateway_vpc }}

- name: Set fact with VPC ID
  ansible.builtin.set_fact:
    __vpc_id: "{{ __aws_vpcs.vpcs.0.vpc_id }}"

- name: Ensure internet gateway is present
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ __vpc_id }}"
    state: present
    tags:
      Name: "{{ item.aws_gateway_name }}"
  when: item.aws_gateway_type == 'igw'