---
- name: Ensure security groups are present
  ansible.builtin.include_tasks:
    file: present.yml
  when: azure_mode == 'provision'

- name: Ensure security groups are absent
  ansible.builtin.include_tasks:
    file: absent.yml
  when: azure_mode == 'deprovision'
 