---
- name: Ensure GCP instances are at desired state
  hosts: gcpclient
  become: false
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        dir: vars
      tags:
        - always

    - name: Ensure instances are present
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_compute_instance
        apply:
          tags:
            - gcp_compute_instance_provision
      loop: "{{ gcp_compute_instances }}"
      loop_control:
        loop_var: gcp_instance
      vars:
        gcp_compute_instance_name: "{{ gcp_instance.gcp_compute_instance_name }}"
        gcp_compute_instance_zone: "{{ gcp_instance.gcp_compute_instance_zone | default(gcp_location) }}"
        gcp_compute_instance_machine_type: "{{ gcp_instance.gcp_compute_instance_machine_type | default(omit) }}"
        gcp_compute_instance_disks: "{{ gcp_instance.gcp_compute_instance_disks | default(omit) }}"
        gcp_compute_instance_network_interfaces: "{{ gcp_instance.gcp_compute_instance_network_interfaces | default(omit) }}"
        gcp_compute_instance_metadata: "{{ gcp_instance.gcp_compute_instance_metadata | default(omit) }}"
        gcp_compute_instance_labels: "{{ gcp_instance.gcp_compute_instance_labels | default(omit) }}"
        gcp_compute_instance_deletion_protection: "{{ gcp_instance.gcp_compute_instance_deletion_protection | default(omit) }}"
        gcp_compute_instance_tags: "{{ gcp_instance.gcp_compute_instance_tags | default(omit) }}"
        gcp_compute_instance_state: "{{ gcp_instance.gcp_compute_instance_state }}"
      when: gcp_instance.gcp_compute_instance_state == 'present'
      tags:
        - gcp_compute_instance_provision

    - name: Ensure instances are absent
      ansible.builtin.include_role:
        name: pumphouse_p.infrastructure.gcp_compute_instance
        apply:
          tags:
            - gcp_compute_instance_deprovision
      loop: "{{ gcp_compute_instances }}"
      loop_control:
        loop_var: gcp_instance
      vars:
        gcp_compute_instance_name: "{{ gcp_instance.gcp_compute_instance_name }}"
        gcp_compute_instance_zone: "{{ gcp_instance.gcp_compute_instance_zone | default(gcp_location) }}"
        gcp_compute_instance_state: "{{ gcp_instance.gcp_compute_instance_state }}"
      when: gcp_instance.gcp_compute_instance_state == 'absent'
      tags:
        - gcp_compute_instance_deprovision
